project_id = "wcxybuietfmaaqzmcmnq"

[functions.validate-description]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.validate-cnae]
verify_jwt = false

[functions.check-correction-deadline]
verify_jwt = false

[functions.validate-oc-value]
verify_jwt = false

[functions.check-sla-alerts]
verify_jwt = false

[functions.check-service-execution]
verify_jwt = false

[functions.whatsmiau-setup]
verify_jwt = false

[functions.whatsapp-daily-digest]
verify_jwt = false

[functions.whatsapp-notify-oc]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
